openapi: 3.0.1
info:
  title: Health Data Analysis Service
  version: 0.1.0
servers:
- url: "http://health-data-service:9090"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /health-data-analysis:
    post:
      operationId: postHealthDataAnalysis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthData'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthData'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    HealthData:
      required:
      - health_data
      - user_id
      type: object
      properties:
        user_id:
          type: string
        health_data:
          $ref: '#/components/schemas/HealthStat'
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    HealthStat:
      required:
      - activity_level
      - blood_pressure
      - heart_rate
      - sleep_duration
      - steps
      type: object
      properties:
        activity_level:
          type: string
        sleep_duration:
          type: string
        heart_rate:
          type: integer
          format: int64
        steps:
          type: string
        blood_pressure:
          type: string
