openapi: 3.0.1
info:
  title: Wellness Recommendation Service
  version: 0.1.0
servers:
- url: "http://wellness-recommendation-service:9090"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /wellness-recommendation:
    get:
      operationId: getWellnessRecommendation
      parameters:
      - name: user_id
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WellnessData'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    MentalWellness:
      required:
      - mindfulness_exercises
      - stress_management
      type: object
      properties:
        mindfulness_exercises:
          $ref: '#/components/schemas/MindfulnessExercises'
        stress_management:
          type: string
    WellnessData:
      required:
      - user_id
      - wellness_recommendations
      type: object
      properties:
        user_id:
          type: string
        wellness_recommendations:
          $ref: '#/components/schemas/WellnessRecommendations'
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    MindfulnessExercises:
      required:
      - mindfulness_exercises
      type: object
      properties:
        mindfulness_exercises:
          type: array
          items:
            $ref: '#/components/schemas/MindfulnessExercise'
    PhysicalWellness:
      required:
      - exercise
      - nutrition
      type: object
      properties:
        exercise:
          type: string
        nutrition:
          type: string
    WellnessRecommendations:
      required:
      - mental_wellness
      - physical_wellness
      type: object
      properties:
        physical_wellness:
          $ref: '#/components/schemas/PhysicalWellness'
        mental_wellness:
          $ref: '#/components/schemas/MentalWellness'
    MindfulnessExercise:
      required:
      - duration
      - name
      type: object
      properties:
        name:
          type: string
        duration:
          type: string
