apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: apk
spec:
  selector:
    matchLabels:
      app: jaeger
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 16686
            - containerPort: 9411
            - containerPort: 4317
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: "9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: apk
spec:
  ports:
    - name: http
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: collector
      protocol: TCP
      port: 9411
      targetPort: 9411
    - name: otlp
      protocol: TCP
      port: 4317
      targetPort: 4317
  selector:
    app: jaeger
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
spec:
  ingressClassName: nginx
  rules:
    - host: jaeger.example.com  
      http:
        paths:
          - path: /api/v2/spans 
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  name: collector
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  name: http
